#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.1'

services:
  wp:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins:z
      - ./wp-content/themes:/var/www/html/wp-content/themes:z
    ports:
      - 8080:80
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisisnotthepw
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: wp
      PMA_PASSWORD: secret
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 8192
    restart: always
    ports:
      - 8088:80
